# Generated by Django 4.2 on 2023-04-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='intro',
        ),
    ]
